const CONFIG = {
  GOOGLE_APPS_SCRIPT_URL: "", // Indsæt Web App URL her
  LODGE_NAME: "Broderloge nr. 35 Concordia"
};

const state = { events: [], members: [], rows: [], signups: {}, currentEvent: null, currentChoice: {}, deferredInstallPrompt: null };
const els = {
  memberSelect: document.getElementById('memberSelect'), saveMemberBtn: document.getElementById('saveMemberBtn'), syncStatus: document.getElementById('syncStatus'),
  installBtn: document.getElementById('installBtn'), eventsList: document.getElementById('eventsList'), totalEvents: document.getElementById('totalEvents'), myAttending: document.getElementById('myAttending'), myMeals: document.getElementById('myMeals'),
  modalBackdrop: document.getElementById('modalBackdrop'), closeModalBtn: document.getElementById('closeModalBtn'), modalDate: document.getElementById('modalDate'), modalTitle: document.getElementById('modalTitle'), modalDescription: document.getElementById('modalDescription'),
  mealBlock: document.getElementById('mealBlock'), guestBlock: document.getElementById('guestBlock'), guestYes: document.getElementById('guestYes'), guestDetails: document.getElementById('guestDetails'), guestName: document.getElementById('guestName'), guestMeal: document.getElementById('guestMeal'), noteInput: document.getElementById('noteInput'), saveSignupBtn: document.getElementById('saveSignupBtn'), saveStatus: document.getElementById('saveStatus'),
  kitchenBtn: document.getElementById('kitchenBtn'), kitchenBackdrop: document.getElementById('kitchenBackdrop'), closeKitchenBtn: document.getElementById('closeKitchenBtn'), kitchenOverview: document.getElementById('kitchenOverview')
};
const storage = { get member(){try{return JSON.parse(localStorage.getItem('concordia_member_v3')||'null')}catch{return null}}, set member(v){localStorage.setItem('concordia_member_v3',JSON.stringify(v))}, get signups(){try{return JSON.parse(localStorage.getItem('concordia_signups_v3')||'{}')}catch{return {}}}, set signups(v){localStorage.setItem('concordia_signups_v3',JSON.stringify(v))} };
const dateFmt = new Intl.DateTimeFormat('da-DK',{weekday:'long',day:'numeric',month:'long',year:'numeric'}); const shortMonthFmt = new Intl.DateTimeFormat('da-DK',{month:'short'});
init();
async function init(){ state.signups=storage.signups; state.events=await loadEvents(); bind(); setupInstall(); registerSW(); await refreshFromSheet(); renderMembers(); render(); }
async function loadEvents(){ const r=await fetch('events.json',{cache:'no-store'}); const ev=await r.json(); return ev.filter(e=>!isPast(e.date)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)); }
function bind(){ els.saveMemberBtn.addEventListener('click',saveMember); els.memberSelect.addEventListener('change',saveMember); els.closeModalBtn.addEventListener('click',closeModal); els.modalBackdrop.addEventListener('click',e=>{if(e.target===els.modalBackdrop)closeModal()}); document.querySelectorAll('[data-attending]').forEach(b=>b.addEventListener('click',()=>chooseAttending(b.dataset.attending))); document.querySelectorAll('[data-meal]').forEach(b=>b.addEventListener('click',()=>chooseMeal(b.dataset.meal))); els.guestYes.addEventListener('change',syncGuest); els.saveSignupBtn.addEventListener('click',saveSignup); els.kitchenBtn.addEventListener('click',openKitchen); els.closeKitchenBtn.addEventListener('click',()=>els.kitchenBackdrop.hidden=true); els.kitchenBackdrop.addEventListener('click',e=>{if(e.target===els.kitchenBackdrop)els.kitchenBackdrop.hidden=true}); els.installBtn.addEventListener('click',installApp); }
async function refreshFromSheet(){ if(!CONFIG.GOOGLE_APPS_SCRIPT_URL){ state.members=fallbackMembers(); els.syncStatus.textContent='Ikke koblet på Google Sheet endnu. Bruger lokal testdata.'; return; } try{ els.syncStatus.textContent='Henter fra Google Sheet…'; const res=await fetch(`${CONFIG.GOOGLE_APPS_SCRIPT_URL}?action=list&t=${Date.now()}`,{cache:'no-store'}); const data=await res.json(); state.members=Array.isArray(data.members)?data.members:fallbackMembers(); state.rows=Array.isArray(data.rows)?data.rows:[]; mergeCurrentUserRows(); els.syncStatus.textContent='Koblet på Google Sheet.'; }catch(err){ console.warn(err); state.members=fallbackMembers(); els.syncStatus.textContent='Kunne ikke hente fra Google Sheet. Lokal visning bruges.'; } }
function renderMembers(){ const current=storage.member; els.memberSelect.innerHTML='<option value="">Vælg navn</option>'+state.members.map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join(''); if(current) els.memberSelect.value=current.id; }
function saveMember(){ const id=els.memberSelect.value; const member=state.members.find(m=>String(m.id)===String(id)); if(!member) return; storage.member={id:String(member.id),name:member.name}; mergeCurrentUserRows(); render(); }
function mergeCurrentUserRows(){ const member=storage.member; if(!member||!state.rows.length)return; const latest=getLatestRows(state.rows); Object.values(latest).forEach(row=>{ if(String(row.memberId)===String(member.id)) state.signups[row.eventId]=normalizeRow(row); }); storage.signups=state.signups; }
function render(){ const member=storage.member; els.totalEvents.textContent=state.events.length; els.myAttending.textContent=Object.values(state.signups).filter(s=>s.attending==='yes').length; els.myMeals.textContent=Object.values(state.signups).filter(s=>s.attending==='yes'&&s.meal==='yes').length; els.eventsList.innerHTML=state.events.map(event=>{ const signup=state.signups[event.id]; const status=getStatus(signup); const summary=getSummary(event.id); const d=new Date(`${event.date}T12:00:00`); return `<article class="event-card" tabindex="0" role="button" data-event-id="${esc(event.id)}"><div class="date-badge"><span class="day">${d.getDate()}</span><span class="month">${shortMonthFmt.format(d).replace('.','')}</span></div><div><h3>${esc(event.title)}</h3><p class="event-meta">${cap(dateFmt.format(d))} · kl. ${event.time.replace(':','.')} · ${esc(event.category)}</p>${event.description?`<p class="event-description">${esc(event.description)}</p>`:''}<p class="event-counts">Deltagere: ${summary.attending} · Spiser: ${summary.meals}${summary.guestMeals?` · Gæster spiser: ${summary.guestMeals}`:''}</p></div><span class="status-pill ${status.className}">${status.label}</span></article>` }).join(''); els.eventsList.querySelectorAll('.event-card').forEach(c=>{c.addEventListener('click',()=>openModal(c.dataset.eventId)); c.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')openModal(c.dataset.eventId)})}); if(!member) els.syncStatus.textContent = CONFIG.GOOGLE_APPS_SCRIPT_URL ? 'Vælg dit navn for at starte.' : els.syncStatus.textContent; }
function openModal(eventId){ const member=storage.member; if(!member){ els.memberSelect.focus(); return; } const event=state.events.find(e=>e.id===eventId); const existing=state.signups[eventId]||{}; state.currentEvent=event; state.currentChoice={attending:existing.attending||null,meal:existing.meal||null,guest:existing.guest==='yes',guestName:existing.guestName||'',guestMeal:existing.guestMeal==='yes',note:existing.note||''}; const d=new Date(`${event.date}T12:00:00`); els.modalDate.textContent=`${cap(dateFmt.format(d))} · kl. ${event.time.replace(':','.')}`; els.modalTitle.textContent=event.title; els.modalDescription.textContent=event.description||'Vælg din tilmelding.'; els.guestBlock.hidden=!event.allowGuests; els.noteInput.value=state.currentChoice.note; els.saveStatus.textContent=''; syncChoices(); els.modalBackdrop.hidden=false; }
function closeModal(){ els.modalBackdrop.hidden=true; state.currentEvent=null; }
function chooseAttending(v){ state.currentChoice.attending=v; if(v==='no'){ state.currentChoice.meal='no'; state.currentChoice.guest=false; state.currentChoice.guestName=''; state.currentChoice.guestMeal=false; } syncChoices(); }
function chooseMeal(v){ if(state.currentChoice.attending!=='yes')return; state.currentChoice.meal=v; syncChoices(); }
function syncGuest(){ state.currentChoice.guest=els.guestYes.checked; if(!state.currentChoice.guest){ state.currentChoice.guestName=''; state.currentChoice.guestMeal=false; } syncChoices(); }
function syncChoices(){ document.querySelectorAll('[data-attending]').forEach(b=>b.classList.toggle('active',b.dataset.attending===state.currentChoice.attending)); document.querySelectorAll('[data-meal]').forEach(b=>{b.classList.toggle('active',b.dataset.meal===state.currentChoice.meal); b.disabled=state.currentChoice.attending!=='yes'}); els.mealBlock.style.opacity=state.currentChoice.attending==='yes'?'1':'.55'; els.guestYes.checked=!!state.currentChoice.guest; els.guestYes.disabled=state.currentChoice.attending!=='yes'; els.guestDetails.hidden=!state.currentChoice.guest||state.currentChoice.attending!=='yes'; els.guestName.value=state.currentChoice.guestName||''; els.guestMeal.checked=!!state.currentChoice.guestMeal; }
async function saveSignup(){ const member=storage.member; if(!member||!state.currentEvent)return; if(!state.currentChoice.attending){ els.saveStatus.textContent='Vælg om du deltager eller ej.'; return; } if(state.currentChoice.attending==='yes'&&!state.currentChoice.meal){ els.saveStatus.textContent='Vælg om du spiser med eller ej.'; return; } const signup={memberId:member.id,name:member.name,eventId:state.currentEvent.id,eventDate:state.currentEvent.date,eventTime:state.currentEvent.time,eventTitle:state.currentEvent.title,attending:state.currentChoice.attending,meal:state.currentChoice.attending==='yes'?state.currentChoice.meal:'no',guest:state.currentChoice.attending==='yes'&&els.guestYes.checked?'yes':'no',guestName:state.currentChoice.attending==='yes'&&els.guestYes.checked?els.guestName.value.trim():'',guestMeal:state.currentChoice.attending==='yes'&&els.guestYes.checked&&els.guestMeal.checked?'yes':'no',note:els.noteInput.value.trim(),updatedAt:new Date().toISOString()}; state.signups[signup.eventId]=signup; storage.signups=state.signups; render(); if(CONFIG.GOOGLE_APPS_SCRIPT_URL){ try{ els.saveStatus.textContent='Gemmer…'; const res=await fetch(CONFIG.GOOGLE_APPS_SCRIPT_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(signup)}); const data=await res.json(); if(!data.ok) throw new Error(data.error||'Ukendt fejl'); els.saveStatus.textContent='Gemt i Google Sheet.'; await refreshFromSheet(); render(); setTimeout(closeModal,500); }catch(err){ console.warn(err); els.saveStatus.textContent='Kunne ikke gemme i Google Sheet. Valget er gemt lokalt på enheden.'; } } else { els.saveStatus.textContent='Gemt lokalt. Indsæt Apps Script URL for Google Sheet.'; setTimeout(closeModal,600); } }
function openKitchen(){ const latest=getLatestRows([...state.rows,...Object.values(state.signups)]); const byEvent={}; Object.values(latest).forEach(r=>{ if(r.attending!=='yes')return; (byEvent[r.eventId] ||= []).push(r); }); els.kitchenOverview.innerHTML=state.events.map(event=>{ const rows=(byEvent[event.id]||[]).sort((a,b)=>a.name.localeCompare(b.name,'da')); const meals=rows.filter(r=>r.meal==='yes').length; const guests=rows.filter(r=>r.guest==='yes').length; const guestMeals=rows.filter(r=>r.guestMeal==='yes').length; const d=new Date(`${event.date}T12:00:00`); return `<div class="kitchen-event"><h3>${esc(event.title)}</h3><p class="event-meta">${cap(dateFmt.format(d))} · kl. ${event.time.replace(':','.')}</p><div class="kitchen-stats"><span>Deltagere: ${rows.length}</span><span>Brødre spiser: ${meals}</span><span>Gæster: ${guests}</span><span>Gæster spiser: ${guestMeals}</span><span>Kuverter i alt: ${meals+guestMeals}</span></div>${rows.length?`<ol class="name-list">${rows.map(r=>`<li>${esc(r.name)}${r.meal==='yes'?' · mad':''}${r.guest==='yes'?` · gæst: ${esc(r.guestName||'uden navn')}${r.guestMeal==='yes'?' (spiser)':''}`:''}</li>`).join('')}</ol>`:'<p class="muted">Ingen tilmeldte endnu.</p>'}</div>` }).join('')||'<div class="empty">Ingen data endnu.</div>'; els.kitchenBackdrop.hidden=false; }
function getSummary(eventId){ const latest=getLatestRows([...state.rows,...Object.values(state.signups)]); const rows=Object.values(latest).filter(r=>r.eventId===eventId&&r.attending==='yes'); return {attending:rows.length,meals:rows.filter(r=>r.meal==='yes').length,guestMeals:rows.filter(r=>r.guestMeal==='yes').length}; }
function getLatestRows(rows){ const latest={}; rows.forEach(r=>{ if(!r||!r.eventId)return; const key=`${r.eventId}__${r.memberId||norm(r.name)}`; if(!latest[key]||new Date(r.updatedAt||0)>=new Date(latest[key].updatedAt||0)) latest[key]=r; }); return latest; }
function normalizeRow(r){ return {memberId:String(r.memberId||''),name:r.name||'',eventId:r.eventId,eventDate:r.eventDate,eventTime:r.eventTime,eventTitle:r.eventTitle,attending:r.attending,meal:r.meal,guest:r.guest||'no',guestName:r.guestName||'',guestMeal:r.guestMeal||'no',note:r.note||'',updatedAt:r.updatedAt}; }
function getStatus(s){ if(!s) return {label:'Ikke valgt',className:'status-none'}; if(s.attending==='no') return {label:'Deltager ikke',className:'status-no'}; if(s.attending==='yes'&&s.meal==='yes') return {label:s.guest==='yes'?'Deltager + mad + gæst':'Deltager + mad',className:'status-yes'}; if(s.attending==='yes') return {label:s.guest==='yes'?'Deltager uden mad + gæst':'Deltager uden mad',className:'status-meal-no'}; return {label:'Ikke valgt',className:'status-none'}; }
function fallbackMembers(){ return [{id:'1',name:'Peter Andersen'},{id:'2',name:'Lars Møller Andersen'},{id:'3',name:'Ivar Lind Bendixen'},{id:'4',name:'Mone Brandstrup'},{id:'5',name:'Christian Peter Brandstrup'},{id:'6',name:'Svend Erik Christensen'},{id:'7',name:'Jens Carsten Kilian Christiansen'},{id:'8',name:'Mogens Dahl'},{id:'9',name:'Anton Edholm'},{id:'10',name:'Per Egekjær'},{id:'11',name:'Ib Kurt Grøn'},{id:'12',name:'Bjarne Halleby Hansen'},{id:'13',name:'Lars Rohde Hansen'},{id:'14',name:'Finn Hansen'},{id:'15',name:'Lars Bo Hansen'},{id:'16',name:'Ole John Hansen'},{id:'17',name:'Bent Kragh Jacobsen'},{id:'18',name:'Kurt Jensen'},{id:'19',name:'Claus Johnny Johansen'},{id:'20',name:'Kim Karlsson'},{id:'21',name:'John Kristensen'},{id:'22',name:'Bøje Skov Larsen'},{id:'23',name:'Niels-Ebbe Dalsø Larsen'},{id:'24',name:'Per Henchel Madsen'},{id:'25',name:'Bjørn Mikkelsen'},{id:'26',name:'Hans Nielsen'},{id:'27',name:"Henry O'Connor"},{id:'28',name:'Lars Weide Olsen'},{id:'29',name:'Daniel Holm Olsen'},{id:'30',name:'Freddy Tage Ottosen'},{id:'31',name:'Gert Sunesen'},{id:'32',name:'Henning Søndermølle'},{id:'33',name:'Torben Møller Sørensen'}]; }
function setupInstall(){ window.addEventListener('beforeinstallprompt',e=>{ e.preventDefault(); state.deferredInstallPrompt=e; els.installBtn.hidden=false; }); window.addEventListener('appinstalled',()=>{els.installBtn.hidden=true; state.deferredInstallPrompt=null;}); }
async function installApp(){ if(!state.deferredInstallPrompt)return; state.deferredInstallPrompt.prompt(); await state.deferredInstallPrompt.userChoice; state.deferredInstallPrompt=null; els.installBtn.hidden=true; }
function registerSW(){ if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js').catch(console.warn); }
function isPast(date){ const today=new Date(); today.setHours(0,0,0,0); return new Date(`${date}T23:59:59`) < today; }
function esc(v){ return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])); } function cap(s){return s?String(s).charAt(0).toUpperCase()+String(s).slice(1):''} function norm(s){return String(s||'').trim().toLowerCase().replace(/\s+/g,' ')}
